# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WordleCli < Formula
  desc "Play wordle in cli"
  homepage "https://github.com/ashish336b/wordle-cli"
  version "0.0.12"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ashish336b/wordle-cli/releases/download/v0.0.12/wordle-cli_0.0.12_Darwin_arm64.tar.gz"
      sha256 "c9499dba47dd69837bc299bdb5953c6621de875ec70ef644a66b4afa96dac36c"

      def install
        bin.install "wordle-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ashish336b/wordle-cli/releases/download/v0.0.12/wordle-cli_0.0.12_Darwin_x86_64.tar.gz"
      sha256 "583a46d35c844ee646c2134b9ff80bbeb477f026214722181289a037ad59a375"

      def install
        bin.install "wordle-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ashish336b/wordle-cli/releases/download/v0.0.12/wordle-cli_0.0.12_Linux_x86_64.tar.gz"
      sha256 "2f406881fb3fd1b3c8b37e42e86068f491087ff63c003acd4f4a50102749d92c"

      def install
        bin.install "wordle-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ashish336b/wordle-cli/releases/download/v0.0.12/wordle-cli_0.0.12_Linux_arm64.tar.gz"
      sha256 "433cd4fc80e7e9883e2ffe5cca7e0f23aa0056ca7576e7281bd322461262e6d9"

      def install
        bin.install "wordle-cli"
      end
    end
  end
end
