# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wordle < Formula
  desc "Play wordle in cli"
  homepage "https://github.com/ashish336b/homebrew-wordle"
  version "0.0.15"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ashish336b/wordle/releases/download/v0.0.15/wordle_0.0.15_Darwin_x86_64.tar.gz"
      sha256 "cc3e2b5c5d9bc5a2a22a2bef3c2e322fe3ad76f56b4c0f91321bdc4e8fc22e72"

      def install
        bin.install "wordle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ashish336b/wordle/releases/download/v0.0.15/wordle_0.0.15_Darwin_arm64.tar.gz"
      sha256 "45a20a1fc2e9fc7ef8bd7e8e29c3c0fabf9f8973b972608d1ffa8b4e76bacef0"

      def install
        bin.install "wordle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ashish336b/wordle/releases/download/v0.0.15/wordle_0.0.15_Linux_x86_64.tar.gz"
      sha256 "05355ea586c55eabacbf3747958d3075c5d775ebba998e721d88563121ecfccf"

      def install
        bin.install "wordle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ashish336b/wordle/releases/download/v0.0.15/wordle_0.0.15_Linux_arm64.tar.gz"
      sha256 "5cd9a5405ee1e9ff708ae3e32524e0a8ce2c90e42b3a0e98406146b22ce3ffa9"

      def install
        bin.install "wordle"
      end
    end
  end
end
