# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wordle < Formula
  desc "Play wordle in cli"
  homepage "https://github.com/ashish336b/wordle"
  version "0.0.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ashish336b/wordle/releases/download/v0.0.14/wordle_0.0.14_Darwin_x86_64.tar.gz"
      sha256 "f7244b152b31c5ec023769c9bef80fc0a985d116f650a47e1e096a2db5ac74c0"

      def install
        bin.install "wordle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ashish336b/wordle/releases/download/v0.0.14/wordle_0.0.14_Darwin_arm64.tar.gz"
      sha256 "fab949097b2e19fef2f4fa09f62b3ce2c7c377683652648409103097ccd202e3"

      def install
        bin.install "wordle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ashish336b/wordle/releases/download/v0.0.14/wordle_0.0.14_Linux_x86_64.tar.gz"
      sha256 "895957896ebf00d9e6e17e49f424d5f74080e4c1e3a65c0d90911766f721b117"

      def install
        bin.install "wordle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ashish336b/wordle/releases/download/v0.0.14/wordle_0.0.14_Linux_arm64.tar.gz"
      sha256 "be182221240c669ee0969743584d42ae50645cab3c318c1fe293c699df293e9b"

      def install
        bin.install "wordle"
      end
    end
  end
end
