# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WordleCli < Formula
  desc "Play wordle in cli"
  homepage "https://github.com/ashish336b/wordle-cli"
  version "0.0.13"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ashish336b/wordle-cli/releases/download/v0.0.13/wordle-cli_0.0.13_Darwin_arm64.tar.gz"
      sha256 "bd548e9f88b1d39e95ff2c780a453c52325ea9f7f012075f2fea1a4b111bbb97"

      def install
        bin.install "wordle-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ashish336b/wordle-cli/releases/download/v0.0.13/wordle-cli_0.0.13_Darwin_x86_64.tar.gz"
      sha256 "a5dd5e4884bbbff7fc541ff23ac0b4114acd87662b51386da9e9274b60ebb9de"

      def install
        bin.install "wordle-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ashish336b/wordle-cli/releases/download/v0.0.13/wordle-cli_0.0.13_Linux_x86_64.tar.gz"
      sha256 "7f1381d3158f951f3791e8bc3b174ba28410656dc83010ad720490bbabdbef56"

      def install
        bin.install "wordle-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ashish336b/wordle-cli/releases/download/v0.0.13/wordle-cli_0.0.13_Linux_arm64.tar.gz"
      sha256 "bf0a0d2f8306f540d1876c21394f0ab027681539c69c83a25c952104a2fdd6d7"

      def install
        bin.install "wordle-cli"
      end
    end
  end
end
